# This is a config for E2B sandbox template.
# You can use template ID (qblli2r8uklpqsetmsfr) or template name (nirmanus-computer-agent) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nirmanus-computer-agent") # Sync sandbox
# sandbox = await AsyncSandbox.create("nirmanus-computer-agent") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nirmanus-computer-agent')

team_id = "3f8a7683-4afc-4553-8238-ff3be4a51624"
memory_mb = 8012
cpu_count = 4
start_cmd = "sh /home/user/agent/start.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nirmanus-computer-agent"
template_id = "qblli2r8uklpqsetmsfr"
