# This is a config for E2B sandbox template.
# You can use template ID (qblli2r8uklpqsetmsfr) or template name (nirmanus-e2b-goose) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nirmanus-e2b-goose") # Sync sandbox
# sandbox = await AsyncSandbox.create("nirmanus-e2b-goose") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nirmanus-e2b-goose')

team_id = "3f8a7683-4afc-4553-8238-ff3be4a51624"
memory_mb = 4_048
cpu_count = 4
start_cmd = "goose --version"
dockerfile = "e2b.Dockerfile"
template_name = "nirmanus-e2b-goose"
template_id = "qblli2r8uklpqsetmsfr"
