extensions:
  coding-toolkit:
    cmd: uvx
    args:
    - '--from'
    - 'cased-kit'
    - 'kit-dev-mcp'
    available_tools: []
    bundled: null
    description: This toolkit allows for coding simple or complex software.
    enabled: true
    env_keys: []
    name: coding-toolkit
    timeout: 500
    type: stdio
  developer:
    available_tools: []
    bundled: true
    description: null
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  filesystem:
    args:
    - -y
    - '@modelcontextprotocol/server-filesystem'
    - /home/user
    available_tools: []
    bundled: null
    cmd: npx
    description: This toolkit allows for file system operations.
    enabled: true
    env_keys: []
    envs: {}
    name: filesystem
    timeout: 500
    type: stdio
  task-manager:
    args:
    - /home/user/mcp-shrimp-task-manager/dist/index.js
    available_tools: []
    bundled: null
    cmd: node
    description: Shrimp task manager MCP entrypoint.
    enabled: true
    env_keys: []
    envs:
        DATA_DIR: /home/user/mcp-shrimp-task-manager/shrimp_data
        ENABLE_GUI: 'false'
        TEMPLATES_USE: en
    name: task-manager
    timeout: 500
    type: stdio
  web-browser-automation:
    args:
    - '@playwright/mcp@latest'
    available_tools: []
    bundled: null
    cmd: npx
    description: An MCP server to perform any complex web browser based workflows or task.
    enabled: true
    env_keys: []
    envs: {}
    name: web-browser-automation
    timeout: 500
    type: stdio
GOOSE_PROVIDER: litellm
GOOSE_MODEL: openrouter/z-ai/glm-4.6
